openapi: 3.0.3
info:
  title: Care Chat API
  description: A chatbot API for care proivders.
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
paths:
  /healthcheck:
    get:
      summary: Healthcheck
      description: Check the health of the API.
      responses:
        '200':
          description: API is healthy.
   /api/room:
    get:
      summary: Retrieve Chat Room
      description: Retrieves a chat room for the current user.
      parameters:
        - in: query
          name: messageLimit
          schema:
            type: integer
            minimum: 1
          description: The number of messages to return.
      responses:
        '200':
          description: Chat room retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The room's ID.
                  botId:
                    type: string
                    description: The ID of the bot in the room.
                  participantIds:
                    type: array
                    items:
                      type: string
                    description: A list of participant user IDs.
                  createdAt:
                    type: string
                    format: date-time
                    description: The timestamp when the room was created.
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: The message's ID.
                        userId:
                          type: string
                          description: The ID of the user who sent the message.
                        text:
                          type: string
                          description: The message text.
                        createdAt:
                          type: string
                          format: date-time
                          description: The timestamp when the message was created.
